
import java.awt.Image;
import java.io.File;
import java.util.StringTokenizer;
import javax.swing.*;
import static javax.swing.text.html.HTML.Tag.OPTION;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himanshi
 */
public class Admin_home extends javax.swing.JFrame {

    JFileChooser jfc;
    File ph,ph1; 
    
    /**
     * Creates new form Admin_home
     */
    public Admin_home(String name) {
         jfc = new JFileChooser();
        initComponents();
        setSize(800,631);
        lb.setText("Welcome "+name);
        
        loadcategories();
        ImageIcon ic = new ImageIcon("src/photos/adminb.jpg");
        Image im = ic.getImage().getScaledInstance(background.getWidth(),background.getHeight(), Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(im));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        catname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        director = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cast = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb.setFont(new java.awt.Font("Goudy Stout", 3, 24)); // NOI18N
        lb.setForeground(new java.awt.Color(153, 0, 255));
        lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb.setText("Welcome");
        getContentPane().add(lb);
        lb.setBounds(0, 0, 800, 50);

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 290, 40);

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 110, 20);

        catname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catnameActionPerformed(evt);
            }
        });
        getContentPane().add(catname);
        catname.setBounds(170, 150, 150, 30);

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Photo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 210, 90, 33);
        getContentPane().add(photo);
        photo.setBounds(140, 260, 120, 110);

        jButton1.setText("choose photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 210, 110, 23);

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 400, 90, 40);

        jLabel4.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Movies");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 80, 300, 40);

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select " }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        getContentPane().add(cb);
        cb.setBounds(490, 150, 210, 30);

        jLabel5.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Movie Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 200, 90, 30);

        jLabel6.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Director");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 250, 80, 30);
        getContentPane().add(mname);
        mname.setBounds(500, 200, 190, 30);

        jLabel7.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Category");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 156, 90, 20);

        director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directorActionPerformed(evt);
            }
        });
        getContentPane().add(director);
        director.setBounds(500, 252, 190, 30);

        jLabel8.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cast");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 300, 90, 30);
        getContentPane().add(cast);
        cast.setBounds(500, 300, 190, 30);

        jLabel9.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Youtube_id");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 346, 90, 30);
        getContentPane().add(id);
        id.setBounds(500, 350, 190, 30);

        jLabel10.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Photo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 480, 90, 30);
        getContentPane().add(p1);
        p1.setBounds(510, 440, 120, 100);

        jButton3.setText("Choose Photo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(640, 490, 110, 23);

        jButton4.setBackground(new java.awt.Color(255, 0, 204));
        jButton4.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(520, 550, 90, 40);

        jLabel11.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Trailer id");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 396, 80, 30);

        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        getContentPane().add(tid);
        tid.setBounds(500, 400, 190, 30);
        getContentPane().add(background);
        background.setBounds(0, 0, 800, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ans = jfc.showOpenDialog(this);
       if(ans== JFileChooser.APPROVE_OPTION)
        {
            ph=jfc.getSelectedFile();
            
            ImageIcon ic = new ImageIcon(ph.getPath());
            Image img = ic.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);
            photo.setIcon(ic1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

     void loadcategories()
    {
        String ans = myClient.fetchcategories();
        
        StringTokenizer st = new StringTokenizer(ans,";;");
        while(st.hasMoreTokens())
        {
            String name = st.nextToken();
            cb.addItem(name);
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = catname.getText();
        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "All feilds are mandatory");
        }
        String ans = myClient.addcategory(name,ph);
        if(ans.equals("success"))
        {
            JOptionPane.showMessageDialog(rootPane, "Category Added");
        }
        else if(ans.equals("exist"))
        {
            JOptionPane.showMessageDialog(rootPane, "Category already exists");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Failed");
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActionPerformed

    private void directorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jfc = new JFileChooser();
        int ans = jfc.showOpenDialog(this);
        if(ans==JFileChooser.APPROVE_OPTION)
        {
            ph1= jfc.getSelectedFile();
            ImageIcon ic = new ImageIcon(ph1.getPath());
            Image img = ic.getImage().getScaledInstance(p1.getWidth(), p1.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);
            p1.setIcon(ic1);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String category=(String)cb.getSelectedItem();
        String movie = mname.getText();
        String direct = director.getText();
        String starcast = cast.getText();
        String uid=id.getText();
        String trid=tid.getText();
        
        if(category.equals("Select Category")||movie.equals("")||direct.equals("")||starcast.equals(" ") ||uid.equals("")||tid.equals("")||ph1==null)
        {
            JOptionPane.showMessageDialog(rootPane, "All Fields are mandatory");
        }
        else
        {
            String ans = myClient.addmovie(category,movie,direct,starcast,uid,trid,ph1);
            if(ans.equals("success"))
            {
                JOptionPane.showMessageDialog(rootPane, "Added");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Failed");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_home("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField cast;
    private javax.swing.JTextField catname;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextField director;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb;
    private javax.swing.JTextField mname;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField tid;
    // End of variables declaration//GEN-END:variables
}
