
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URI;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himanshi
 */
public class movie_detail extends javax.swing.JFrame {

    /**
     * Creates new form movie_detail
     */
    int movie_id;
    public movie_detail(int id) {
        initComponents();
        setSize(1000,500);
        ImageIcon ic = new ImageIcon("src/photos/wbb.jpg");
        Image im = ic.getImage().getScaledInstance(background.getWidth(),background.getHeight(), Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(im));

        movie_id = id;
        loadmovie();
        
    }
    public void loadmovie()
    {
        String ans = myClient.loadmovie(movie_id);
        StringTokenizer st = new StringTokenizer(ans,";;");
        String mname = st.nextToken();
        String director = st.nextToken();
        String cast = st.nextToken();
        String photo = st.nextToken();
        String uid= st.nextToken();
        String tid = st.nextToken();
        
        movielb.setText(mname);
        castlb.setText(cast);
        directorlb.setText(director);
        
        ImageIcon ic = new ImageIcon(photo);
            Image img = ic.getImage().getScaledInstance(photolb.getWidth(),photolb.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);
            photolb.setIcon(ic1);
            
            ImageIcon ic2 = new ImageIcon("src/photos/play1.png");
            Image img2 = ic2.getImage().getScaledInstance(50,45,Image.SCALE_SMOOTH);
            ImageIcon ic3 = new ImageIcon(img2);
            moviebt.setIcon(ic3);
            trailerbt.setIcon(ic3);
            
            castlb.setEnabled(false);
            directorlb.setEnabled(false);
            
            moviebt.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                try 
                {
                    URI uri = new URI("https://www.youtube.com/watch?v="+uid);
                    Desktop d = Desktop.getDesktop();
                    d.browse(uri);
                    
                } 
                catch (Exception e1) 
                {
                    e1.printStackTrace();
                }
                
            }
             });
            
            trailerbt.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                try 
                {
                    URI uri = new URI("https://www.youtube.com/watch?v="+tid);
                    Desktop d = Desktop.getDesktop();
                    d.browse(uri);
                    
                } 
                catch (Exception e1) 
                {
                    e1.printStackTrace();
                }
                
            }
             });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photolb = new javax.swing.JLabel();
        movielb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        directorlb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        castlb = new javax.swing.JTextField();
        trailerbt = new javax.swing.JButton();
        moviebt = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(photolb);
        photolb.setBounds(0, 0, 420, 500);

        movielb.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        movielb.setForeground(new java.awt.Color(255, 51, 51));
        movielb.setText("gdiyfkagyufgiusdgui");
        getContentPane().add(movielb);
        movielb.setBounds(440, 80, 550, 40);

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel3.setText("Director");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 150, 110, 30);

        directorlb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directorlbActionPerformed(evt);
            }
        });
        getContentPane().add(directorlb);
        directorlb.setBounds(520, 150, 450, 30);

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel4.setText("Cast");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 210, 70, 33);
        getContentPane().add(castlb);
        castlb.setBounds(520, 210, 450, 30);

        trailerbt.setBackground(new java.awt.Color(0, 0, 0));
        trailerbt.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        trailerbt.setForeground(new java.awt.Color(255, 255, 255));
        trailerbt.setText("Play Trailer");
        trailerbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trailerbtActionPerformed(evt);
            }
        });
        getContentPane().add(trailerbt);
        trailerbt.setBounds(490, 310, 200, 50);

        moviebt.setBackground(new java.awt.Color(0, 0, 0));
        moviebt.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        moviebt.setForeground(new java.awt.Color(255, 255, 255));
        moviebt.setText("Play Movie");
        getContentPane().add(moviebt);
        moviebt.setBounds(490, 390, 200, 50);
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void directorlbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directorlbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directorlbActionPerformed

    private void trailerbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trailerbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trailerbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie_detail(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField castlb;
    private javax.swing.JTextField directorlb;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton moviebt;
    private javax.swing.JLabel movielb;
    private javax.swing.JLabel photolb;
    private javax.swing.JButton trailerbt;
    // End of variables declaration//GEN-END:variables
}
