
public class Server_ON_OFF extends javax.swing.JFrame {

    myServer obj;
    public Server_ON_OFF() {
        
        initComponents();
        setSize(500,500);
        stopbt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startbt = new javax.swing.JButton();
        stopbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        startbt.setText("Start Server");
        startbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtActionPerformed(evt);
            }
        });
        getContentPane().add(startbt);
        startbt.setBounds(87, 35, 230, 50);

        stopbt.setText("Stop Server");
        stopbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbtActionPerformed(evt);
            }
        });
        getContentPane().add(stopbt);
        stopbt.setBounds(85, 133, 240, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtActionPerformed
       try{
        obj= new myServer(9000);
        startbt.setEnabled(false);
        stopbt.setEnabled(true);
        
        welcome obj1 = new welcome();
        obj1.setVisible(true);
        
       }
       catch (Exception e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_startbtActionPerformed

    private void stopbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbtActionPerformed
        obj.shutdown();
        startbt.setEnabled(true);
        stopbt.setEnabled(false);
    }//GEN-LAST:event_stopbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_ON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_ON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_ON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_ON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_ON_OFF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startbt;
    private javax.swing.JButton stopbt;
    // End of variables declaration//GEN-END:variables
}
