
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himanshi
 */
public class user_home extends javax.swing.JFrame {

    /**
     * Creates new form user_home
     */
    public user_home(String email) {
        initComponents();
        setSize(850,500);
        lb.setText("Welcome: "+email);
        loadcategory();
        mainpanel1.setOpaque(true);
//         ImageIcon ici = new ImageIcon("src/photos/black.jpg");
//        Image imi = ici.getImage().getScaledInstance(background.getWidth(),background.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon ic2 = new ImageIcon(imi);
//        background.setIcon(new ImageIcon(im));
//        mainpanel1.setBackground(red));
    }
    void loadcategory()
    {
        String ans = myClient.fetchcat();
        StringTokenizer st = new StringTokenizer(ans,";;");
        int n= st.countTokens();
        JButton arr[]=new JButton[n];
        JLabel arr1[]=new JLabel[n];
         int x=10,y=50;
         int k=20,j=260;
        for (int i = 0; i < n; i++) 
        {
            String row = st.nextToken();
            StringTokenizer st1 = new StringTokenizer(row,"$");
            
            
            String name = st1.nextToken();
            String photo = st1.nextToken();
            
            arr[i] = new JButton(name);
            arr1[i]=new JLabel(name);
            
            ImageIcon ic = new ImageIcon(photo);
            Image img = ic.getImage().getScaledInstance(255 ,196,Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);
            arr[i].setIcon(ic1);
            
            arr[i].setBounds(x, y, 250, 200);
            arr1[i].setBounds(k, j, 250, 50);
            
            arr[i].addActionListener(new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e) {
                   fetch_movies obj = new fetch_movies(name);
                   obj.setVisible(true);
                   dispose();
                }
            });
            
            mainpanel1.add(arr[i]);
            mainpanel1.add(arr1[i]);
            mainpanel1.repaint();
            
            if(x<=780)
            {
                  x = x+260;
                  k=k+270;
            }
            else
            {
                x=10;
                k=10;
                j=j+270;
                y=y+270;
            }
          
            
        }
        mainpanel1.setPreferredSize(new Dimension(820,n*80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        mainpanel = new javax.swing.JScrollPane();
        mainpanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb.setFont(new java.awt.Font("Goudy Stout", 3, 24)); // NOI18N
        lb.setForeground(new java.awt.Color(255, 0, 102));
        lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb.setText("Welcome");
        getContentPane().add(lb);
        lb.setBounds(-1, 8, 800, 50);

        javax.swing.GroupLayout mainpanel1Layout = new javax.swing.GroupLayout(mainpanel1);
        mainpanel1.setLayout(mainpanel1Layout);
        mainpanel1Layout.setHorizontalGroup(
            mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        mainpanel1Layout.setVerticalGroup(
            mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        mainpanel.setViewportView(mainpanel1);

        getContentPane().add(mainpanel);
        mainpanel.setBounds(0, 60, 790, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_home("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb;
    private javax.swing.JScrollPane mainpanel;
    private javax.swing.JPanel mainpanel1;
    // End of variables declaration//GEN-END:variables
}
